### ISSUE TITLE
Allow alternate root url to webpack

### ISSUE THREAD

**Issue by thomasmckay** [patternfly/patternfly-react-seed#20]
I have _patternfly-react-seed_ running behind nginx which routes /console to it. Hitting that url, I get:
```
GET https://devel.example.com/app.bundle.js/ net::ERR_ABORTED 404
```

The source looks like this (call to _script_ has the error):
```
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>Patternfly Seed</title>
    <meta id="appName" name="application-name" content="Patternfly Seed" />
  </head>

  <body>
    <noscript>Enabling JavaScript is required to run this app.</noscript>
    <div id="root"></div>
  <script type="text/javascript" src="app.bundle.js"></script></body>
</html>
```

**Comment by seanforyou23** [comment]
@thomasmckay I just gave this a run on a stock nginx setup and it seems to work fine. I set the server root to point to the dist directory as follows:

`location / {
    root   /path/to/patternfly-react-seed/dist;
    index  index.html index.htm;
}`

Feel free to share any specific config settings you think may be causing the issue. If there's an issue with seed I'm happy help. Keep in mind it's intended for use as an SPA - so if you're using explicit routes you may need to get creative with an extra build step like maybe rsync the dist directory to a more appropriate location so that the paths make sense. In any case, lemme know if this helps and we'll get you squared away.

**Comment by thomasmckay** [comment]
Thanks for quick response! Here's what I've changed so far:
https://github.com/patternfly/patternfly-react-seed/compare/master...thomasmckay:quay
That works for the change to _/console_.

I get this error now, which I'm unsure how to correct:
```
abstract-xhr.js:132 GET https://localhost:9000/sockjs-node/info?t=1544491694932 net::ERR_CONNECTION_REFUSED
```

I could try redirecting _sockjs-node_ in nginx conf but I'm curious as to what should be handling that route.

**Comment by seanforyou23** [comment]
Hi @thomasmckay - I'm not really sure how to proceed with this. Did you happen to get unstuck here? Otherwise, could you kindly provide some steps I can take to reproduce the problem locally? It sounds like it may not be an issue with the seed project, but I could be mistaken.

**Comment by thomasmckay** [comment]
@seanforyou23 We can close this. If I get the chance to return to pf4 again I will debug and create simpler reproducer. Thanks!
