### ISSUE TITLE
Is there seed project for html/css

### ISSUE THREAD

**Issue by ishuverma** [patternfly/patternfly-react-seed#79]
In v3, there was a seed code for html/css but I don't see any in the v4.

**Comment by seanforyou23** [comment]
Hi @ishuverma - yea, I think the idea was that users can be shielded from some of the daily churn of the html/css API by using the react components. If you're using html/css I'd recommend checking out one of the full page demos to get started https://www.patternfly.org/v4/documentation/core/demos/page Does this help enough?

Fwiw, you could certainly use this build architecture to write html/css if you're ok with writing in JSX for the markup.. It would allow you to leverage all the existing build tooling and upgrade to react later if you choose.

Otherwise, might be worth opening up an issue in core since this repo is geared toward supporting react, webpack, and typescript specifically. Let me know if this makes sense!
