### ISSUE TITLE
Remove storybook from  patternfly-seed-application

### ISSUE THREAD

**Issue by ddonahue007** [patternfly/patternfly-react-seed#80]
The seed application should be streamlined for startup applications and not component development.

- Remove storybook

Reference this task as including storybook was a feature request.

https://github.com/patternfly/patternfly-react-seed/pull/66

**Comment by riccardo-forina** [comment]
I can't say that I agree. Most projects require custom components and those are best developed in isolation in Storybook. Given that adding Storybook to the seed project wasn't a trivial operation, I think it does make sense to provide a ready-to-work-with solution for the average guy out there that doesn't want to mess with webpack & co.

Just my 2¢ ofc.

**Comment by seanforyou23** [comment]
These are all valid viewpoints. This seed project, while serving nicely these days as a project starter, was born out of the need for an example of how to _configure_ projects using patternfly/patternfly-react from a build perspective. Webpack was the common build tool that questions kept coming up about so we chose that as the base for the seed project to serve as example configuration. I think since the additional storybook related code and footprint are small, and yet solve an otherwise fairly intricate integration/config task (and elegantly) it makes sense to keep it.

It's a good point though, I imagine plenty of people may not necessarily need things like testing, bundle analyzers, and nested component demo apps. I'd be happy to add a section of doc that explains how to remove optional features like this for those who don't need/want them - probably a one-liner assuming you're not on windoze 😉@ddonahue007 does that sound like an ok solution to you?

**Comment by seanforyou23** [comment]
I thought adding a wiki entry might be a better place to start https://github.com/patternfly/patternfly-react-seed/wiki/How-to-remove-things-you-don't-need

I'll add info for jest, prettier, and eslint if everyone thinks it's generally an ok format
